#!/bin/bash

# Runs the server with live compilation of sass/coffeescript
set -e
set -a

# Close all child processes on exit
function on_quit {
    kill `jobs -p`
}

trap on_quit EXIT

# Run the server
./scripts/using-profile dev server &

# Start SASS/coffee live compilation
sass --watch static/sass:static/css &

pushd static
    coffee --watch --map --output js coffeescript &
popd

while true; do read x; done
